use bg9t0e0iz68ihwvbk2hm;

CREATE TABLE `ASSINATURAS` (
  `ID_ASSINATURA` int NOT NULL AUTO_INCREMENT,
  `ID_USUARIO` int NOT NULL,
  `PLANO` varchar(20) NOT NULL,
  `STATUS_PAGAMENTO` varchar(20) DEFAULT NULL,
  `ID_PAGAMENTO` varchar(50) DEFAULT NULL,
  `DATA_INICIO` datetime NOT NULL,
  `DATA_FIM` datetime DEFAULT NULL,
  PRIMARY KEY (`ID_ASSINATURA`),
  KEY `ID_USUARIO` (`ID_USUARIO`),
  CONSTRAINT `ASSINATURAS_ibfk_1` FOREIGN KEY (`ID_USUARIO`) 
      REFERENCES `USUARIOS` (`ID_USUARIO`)
) ENGINE=InnoDB 
  AUTO_INCREMENT=15 
  DEFAULT CHARSET=utf8;



DROP TABLE IF EXISTS `COMENTARIOS`;

CREATE TABLE `COMENTARIOS` (
  `ID_COMENTARIO` int NOT NULL AUTO_INCREMENT,
  `ID_USUARIO` int NOT NULL,
  `ID_PUBLICACAO` int NOT NULL,
  `CONTEUDO_COMENTARIO` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `DATA_COMENTARIO` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID_COMENTARIO`),
  KEY `ID_USUARIO` (`ID_USUARIO`),
  KEY `ID_PUBLICACAO` (`ID_PUBLICACAO`),
  CONSTRAINT `COMENTARIOS_ibfk_1` FOREIGN KEY (`ID_USUARIO`) 
      REFERENCES `USUARIOS` (`ID_USUARIO`) ON DELETE CASCADE,
  CONSTRAINT `COMENTARIOS_ibfk_2` FOREIGN KEY (`ID_PUBLICACAO`) 
      REFERENCES `PUBLICACOES_PROFISSIONAL` (`ID_PUBLICACAO`) ON DELETE CASCADE
) ENGINE=InnoDB 
  AUTO_INCREMENT=3 
  DEFAULT CHARSET=utf8;



DROP TABLE IF EXISTS `CONTEUDOS_PUBLICACAO_PROFISSIONAL`;

CREATE TABLE `CONTEUDOS_PUBLICACAO_PROFISSIONAL` (
  `ID_PUBLICACAO` int NOT NULL,
  `IMG_PUBLICACAO` longblob,
  KEY `ID_PUBLICACAO` (`ID_PUBLICACAO`),
  CONSTRAINT `CONTEUDOS_PUBLICACAO_PROFISSIONAL_ibfk_1` FOREIGN KEY (`ID_PUBLICACAO`)
      REFERENCES `PUBLICACOES_PROFISSIONAL` (`ID_PUBLICACAO`) ON DELETE CASCADE
) ENGINE=InnoDB 
  DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `CONTRATACOES`;
CREATE TABLE `CONTRATACOES` (
  `ID_CONTRATACAO` int NOT NULL AUTO_INCREMENT,
  `ID_CLIENTE` int DEFAULT NULL,
  `ID_PROFISSIONAL` int DEFAULT NULL,
  `NOME_PROJETO` varchar(255) NOT NULL,
  `DESCRICAO` text,
  `OBSERVACOES` text,
  `VALOR_TOTAL` decimal(10,2) NOT NULL,
  `STATUS` varchar(50) DEFAULT 'AGUARDANDO CONFIRMAÇÃO',
  `DATA_CRIACAO` datetime DEFAULT CURRENT_TIMESTAMP,
  `DATA_ENTREGA` date DEFAULT NULL,
  `DATA_FINALIZACAO` datetime DEFAULT NULL,
  `PAGO` enum('sim','nao') DEFAULT 'nao',
  `ID_USUARIO_CRIADOR` int NOT NULL,
  `CONFIRMACAO_PROFISSIONAL` tinyint(1) DEFAULT 0, -- 0 = não confirmou | 1 = confirmou
  `CONFIRMACAO_CLIENTE` tinyint(1) DEFAULT 0,      -- 0 = não confirmou | 1 = confirmou
  PRIMARY KEY (`ID_CONTRATACAO`),
  KEY `ID_CLIENTE` (`ID_CLIENTE`),
  KEY `ID_PROFISSIONAL` (`ID_PROFISSIONAL`),
  KEY `fk_criador` (`ID_USUARIO_CRIADOR`),
  CONSTRAINT `CONTRATACOES_ibfk_1` FOREIGN KEY (`ID_CLIENTE`) 
      REFERENCES `USUARIOS` (`ID_USUARIO`) ON DELETE SET NULL,
  CONSTRAINT `CONTRATACOES_ibfk_2` FOREIGN KEY (`ID_PROFISSIONAL`) 
      REFERENCES `USUARIOS` (`ID_USUARIO`) ON DELETE SET NULL,
  CONSTRAINT `fk_criador` FOREIGN KEY (`ID_USUARIO_CRIADOR`) 
      REFERENCES `USUARIOS` (`ID_USUARIO`) ON DELETE CASCADE
) ENGINE=InnoDB 
  AUTO_INCREMENT=15 
  DEFAULT CHARSET=utf8;



DROP TABLE IF EXISTS `DENUNCIAS_COMENTARIOS`;

CREATE TABLE `DENUNCIAS_COMENTARIOS` (
  `ID_DENUNCIA` int NOT NULL AUTO_INCREMENT,
  `ID_USUARIO_DENUNCIANTE` int DEFAULT NULL,
  `ID_COMENTARIO` int NOT NULL,
  `MOTIVO` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `STATUS` enum('pendente','analisando','resolvido') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'pendente',
  `DATA_DENUNCIA` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID_DENUNCIA`),
  KEY `ID_USUARIO_DENUNCIANTE` (`ID_USUARIO_DENUNCIANTE`),
  KEY `ID_COMENTARIO` (`ID_COMENTARIO`),
  CONSTRAINT `DENUNCIAS_COMENTARIOS_ibfk_1` FOREIGN KEY (`ID_USUARIO_DENUNCIANTE`) 
      REFERENCES `USUARIOS` (`ID_USUARIO`),
  CONSTRAINT `DENUNCIAS_COMENTARIOS_ibfk_2` FOREIGN KEY (`ID_COMENTARIO`) 
      REFERENCES `COMENTARIOS` (`ID_COMENTARIO`) ON DELETE CASCADE
) ENGINE=InnoDB 
  DEFAULT CHARSET=utf8mb4 
  COLLATE=utf8mb4_unicode_ci;




DROP TABLE IF EXISTS `DENUNCIAS_PROJETOS`;

CREATE TABLE `DENUNCIAS_PROJETOS` (
  `ID_DENUNCIA` int NOT NULL AUTO_INCREMENT,
  `ID_USUARIO_DENUNCIANTE` int NOT NULL,
  `ID_PROJETO` int NOT NULL,
  `MOTIVO` varchar(255) NOT NULL,
  `STATUS` enum('pendente','analisada','rejeitada') DEFAULT 'pendente',
  `DATA_DENUNCIA` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID_DENUNCIA`),
  KEY `ID_USUARIO_DENUNCIANTE` (`ID_USUARIO_DENUNCIANTE`),
  KEY `DENUNCIAS_PROJETOS_ibfk_2` (`ID_PROJETO`),
  CONSTRAINT `DENUNCIAS_PROJETOS_ibfk_1` FOREIGN KEY (`ID_USUARIO_DENUNCIANTE`) 
      REFERENCES `USUARIOS` (`ID_USUARIO`),
  CONSTRAINT `DENUNCIAS_PROJETOS_ibfk_2` FOREIGN KEY (`ID_PROJETO`) 
      REFERENCES `PROPOSTA_PROJETO` (`ID_PROPOSTA`) ON DELETE CASCADE
) ENGINE=InnoDB 
  AUTO_INCREMENT=18 
  DEFAULT CHARSET=utf8;




DROP TABLE IF EXISTS `DENUNCIAS_PUBLICACOES`;

CREATE TABLE `DENUNCIAS_PUBLICACOES` (
  `ID_DENUNCIA` int NOT NULL AUTO_INCREMENT,
  `ID_USUARIO_DENUNCIANTE` int DEFAULT NULL,
  `ID_PUBLICACAO` int NOT NULL,
  `MOTIVO` varchar(255) NOT NULL,
  `STATUS` enum('pendente','analisando','resolvido') DEFAULT 'pendente',
  `DATA_DENUNCIA` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID_DENUNCIA`),
  KEY `ID_USUARIO_DENUNCIANTE` (`ID_USUARIO_DENUNCIANTE`),
  KEY `ID_PUBLICACAO` (`ID_PUBLICACAO`),
  CONSTRAINT `DENUNCIAS_PUBLICACOES_ibfk_1` FOREIGN KEY (`ID_USUARIO_DENUNCIANTE`) 
      REFERENCES `USUARIOS` (`ID_USUARIO`),
  CONSTRAINT `DENUNCIAS_PUBLICACOES_ibfk_2` FOREIGN KEY (`ID_PUBLICACAO`) 
      REFERENCES `CONTEUDOS_PUBLICACAO_PROFISSIONAL` (`ID_PUBLICACAO`)
) ENGINE=InnoDB 
  DEFAULT CHARSET=utf8;



DROP TABLE IF EXISTS `DENUNCIAS_USUARIOS`;

CREATE TABLE `DENUNCIAS_USUARIOS` (
  `ID_DENUNCIA` int NOT NULL AUTO_INCREMENT,
  `ID_USUARIO_DENUNCIANTE` int NOT NULL,
  `ID_USUARIO_DENUNCIADO` int NOT NULL,
  `MOTIVO` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `STATUS` enum('pendente','analisando','resolvido') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'pendente',
  `DATA_DENUNCIA` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID_DENUNCIA`),
  KEY `ID_USUARIO_DENUNCIANTE` (`ID_USUARIO_DENUNCIANTE`),
  KEY `ID_USUARIO_DENUNCIADO` (`ID_USUARIO_DENUNCIADO`),
  CONSTRAINT `DENUNCIAS_USUARIOS_ibfk_1` FOREIGN KEY (`ID_USUARIO_DENUNCIANTE`) 
      REFERENCES `USUARIOS` (`ID_USUARIO`),
  CONSTRAINT `DENUNCIAS_USUARIOS_ibfk_2` FOREIGN KEY (`ID_USUARIO_DENUNCIADO`) 
      REFERENCES `USUARIOS` (`ID_USUARIO`)
) ENGINE=InnoDB 
  AUTO_INCREMENT=13 
  DEFAULT CHARSET=utf8mb4 
  COLLATE=utf8mb4_unicode_ci;



DROP TABLE IF EXISTS `FAVORITOS`;

CREATE TABLE `FAVORITOS` (
  `ID_PUBLICACAO` int NOT NULL,
  `ID_USUARIO` int NOT NULL,
  `DT_INCLUSAO_FAVORITO` date DEFAULT NULL,
  `STATUS_FAVORITO` int DEFAULT '1',
  PRIMARY KEY (`ID_PUBLICACAO`,`ID_USUARIO`),
  KEY `FK_FAVORITO_USUARIO` (`ID_USUARIO`),
  KEY `FK_FAVORITO_PUBLICACAO` (`ID_PUBLICACAO`),
  CONSTRAINT `FK_FAVORITO_PUBLICACAO` FOREIGN KEY (`ID_PUBLICACAO`) 
      REFERENCES `PUBLICACOES_PROFISSIONAL` (`ID_PUBLICACAO`),
  CONSTRAINT `FK_FAVORITO_USUARIO` FOREIGN KEY (`ID_USUARIO`) 
      REFERENCES `USUARIOS` (`ID_USUARIO`)
) ENGINE=InnoDB 
  DEFAULT CHARSET=utf8mb4 
  COLLATE=utf8mb4_unicode_ci;



DROP TABLE IF EXISTS `MENSAGEM`;

CREATE TABLE `MENSAGEM` (
  `ID_MENSAGEM` int NOT NULL AUTO_INCREMENT,
  `REMETENTE_ID` int NOT NULL,
  `DESTINATARIO_ID` int NOT NULL,
  `CONTEUDO` text NOT NULL,
  `DATA_ENVIO` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `STATUS` enum('ENVIADA','ENTREGUE','LIDA') DEFAULT 'ENVIADA',
  PRIMARY KEY (`ID_MENSAGEM`),
  KEY `REMETENTE_ID` (`REMETENTE_ID`),
  KEY `DESTINATARIO_ID` (`DESTINATARIO_ID`),
  CONSTRAINT `MENSAGEM_IBFK_1` FOREIGN KEY (`REMETENTE_ID`) 
      REFERENCES `USUARIOS` (`ID_USUARIO`),
  CONSTRAINT `MENSAGEM_IBFK_2` FOREIGN KEY (`DESTINATARIO_ID`) 
      REFERENCES `USUARIOS` (`ID_USUARIO`)
) ENGINE=InnoDB 
  AUTO_INCREMENT=33 
  DEFAULT CHARSET=utf8mb4 
  COLLATE=utf8mb4_0900_ai_ci;





DROP TABLE IF EXISTS `NOTIFICACOES`;

CREATE TABLE `NOTIFICACOES` (
  `ID_NOTIFICACAO` int NOT NULL AUTO_INCREMENT,
  `TITULO_NOTIFICACAO` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `PREVIEW_NOTIFICACAO` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CONTEUDO_NOTIFICACAO` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `ID_USUARIO` int NOT NULL,
  `CATEGORIA_NOTIFICACAO` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `STATUS` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT 'NAO_LIDA',
  `DATA_CRIACAO_NOTIFICACAO` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID_NOTIFICACAO`),
  KEY `ID_USUARIO` (`ID_USUARIO`),
  CONSTRAINT `NOTIFICACOES_ibfk_1` FOREIGN KEY (`ID_USUARIO`) 
      REFERENCES `USUARIOS` (`ID_USUARIO`)
) ENGINE=InnoDB 
  AUTO_INCREMENT=85 
  DEFAULT CHARSET=utf8mb4 
  COLLATE=utf8mb4_unicode_ci;





DROP TABLE IF EXISTS `PAGAMENTOS_CONTRATACOES`;

CREATE TABLE `PAGAMENTOS_CONTRATACOES` (
  `ID_PAGAMENTO_CONTRATACAO` int NOT NULL AUTO_INCREMENT,
  `ID_CONTRATACAO` int NOT NULL,
  `ID_PAGAMENTO_MERCADO_PAGO` varchar(100) NOT NULL,
  `STATUS_PAGAMENTO` varchar(20) DEFAULT 'pendente',
  `VALOR_PAGO` decimal(10,2) NOT NULL,
  `DATA_PAGAMENTO` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID_PAGAMENTO_CONTRATACAO`),
  KEY `PAGAMENTOS_CONTRATACOES_ibfk_1` (`ID_CONTRATACAO`),
  CONSTRAINT `PAGAMENTOS_CONTRATACOES_ibfk_1` FOREIGN KEY (`ID_CONTRATACAO`) 
      REFERENCES `CONTRATACOES` (`ID_CONTRATACAO`) ON DELETE CASCADE
) ENGINE=InnoDB 
  AUTO_INCREMENT=17 
  DEFAULT CHARSET=utf8;




DROP TABLE IF EXISTS `PORTFOLIOS`;

CREATE TABLE `PORTFOLIOS` (
  `ID_PORTFOLIO` int NOT NULL AUTO_INCREMENT,
  `NOME_PORTFOLIO` varchar(70) NOT NULL,
  `ID_USUARIO` int NOT NULL,
  `DESCRICAO_PORTFOLIO` text,
  PRIMARY KEY (`ID_PORTFOLIO`),
  KEY `ID_USUARIO` (`ID_USUARIO`),
  CONSTRAINT `PORTFOLIOS_ibfk_1` FOREIGN KEY (`ID_USUARIO`) 
      REFERENCES `USUARIOS` (`ID_USUARIO`) ON DELETE CASCADE
) ENGINE=InnoDB 
  DEFAULT CHARSET=utf8;




DROP TABLE IF EXISTS `PROPOSTA_PROJETO`;

CREATE TABLE `PROPOSTA_PROJETO` (
  `ID_PROPOSTA` int NOT NULL AUTO_INCREMENT,
  `ID_USUARIO` int NOT NULL,
  `DATA_PROPOSTA` date NOT NULL,
  `TITULO_PROPOSTA` varchar(70) NOT NULL,
  `DESCRICAO_PROPOSTA` text NOT NULL,
  `CATEGORIA_PROPOSTA` varchar(50) NOT NULL,
  `PREFERENCIA_PROPOSTA` varchar(50) DEFAULT NULL,
  `PRAZO_ENTREGA` date DEFAULT NULL,
  `ORCAMENTO` decimal(10,2) DEFAULT NULL,
  `STATUS_PROPOSTA` enum('Aberta','Fechada','Expirada') NOT NULL,
  PRIMARY KEY (`ID_PROPOSTA`),
  KEY `ID_USUARIO` (`ID_USUARIO`),
  CONSTRAINT `PROPOSTA_PROJETO_ibfk_1` FOREIGN KEY (`ID_USUARIO`) 
      REFERENCES `USUARIOS` (`ID_USUARIO`) ON DELETE CASCADE
) ENGINE=InnoDB 
  AUTO_INCREMENT=2 
  DEFAULT CHARSET=utf8;



DROP TABLE IF EXISTS `PUBLICACAO_PORTFOLIO`;

CREATE TABLE `PUBLICACAO_PORTFOLIO` (
  `ID_PUBLICACAO` int NOT NULL,
  `ID_PORTFOLIO` int NOT NULL,
  PRIMARY KEY (`ID_PUBLICACAO`,`ID_PORTFOLIO`),
  KEY `ID_PORTFOLIO` (`ID_PORTFOLIO`),
  CONSTRAINT `PUBLICACAO_PORTFOLIO_ibfk_1` FOREIGN KEY (`ID_PUBLICACAO`) 
      REFERENCES `PUBLICACOES_PROFISSIONAL` (`ID_PUBLICACAO`) ON DELETE CASCADE,
  CONSTRAINT `PUBLICACAO_PORTFOLIO_ibfk_2` FOREIGN KEY (`ID_PORTFOLIO`) 
      REFERENCES `PORTFOLIOS` (`ID_PORTFOLIO`) ON DELETE CASCADE
) ENGINE=InnoDB 
  DEFAULT CHARSET=utf8;




DROP TABLE IF EXISTS `PUBLICACOES_PROFISSIONAL`;

CREATE TABLE `PUBLICACOES_PROFISSIONAL` (
  `ID_PUBLICACAO` int NOT NULL AUTO_INCREMENT,
  `ID_USUARIO` int NOT NULL,
  `NOME_PUBLICACAO` varchar(70) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `DESCRICAO_PUBLICACAO` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `CATEGORIA` varchar(50) NOT NULL,
  `DATA_PUBLICACAO` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID_PUBLICACAO`),
  KEY `ID_USUARIO` (`ID_USUARIO`),
  CONSTRAINT `PUBLICACOES_PROFISSIONAL_ibfk_1` FOREIGN KEY (`ID_USUARIO`) 
      REFERENCES `USUARIOS` (`ID_USUARIO`) ON DELETE CASCADE
) ENGINE=InnoDB 
  AUTO_INCREMENT=2 
  DEFAULT CHARSET=utf8;




DROP TABLE IF EXISTS `SEGUINDO`;

CREATE TABLE `SEGUINDO` (
  `ID_USUARIO` int NOT NULL,
  `ID_SEGUIDO` int NOT NULL,
  `DT_INCLUSAO_SEGUINDO` datetime DEFAULT CURRENT_TIMESTAMP,
  `STATUS_SEGUINDO` int DEFAULT '1',
  PRIMARY KEY (`ID_USUARIO`,`ID_SEGUIDO`),
  KEY `FK_SEGUINDO_USUARIO` (`ID_USUARIO`),
  KEY `FK_SEGUINDO_SEGUIDO` (`ID_SEGUIDO`),
  CONSTRAINT `FK_SEGUINDO_SEGUIDO` FOREIGN KEY (`ID_SEGUIDO`) 
      REFERENCES `USUARIOS` (`ID_USUARIO`) ON DELETE CASCADE,
  CONSTRAINT `FK_SEGUINDO_USUARIO` FOREIGN KEY (`ID_USUARIO`) 
      REFERENCES `USUARIOS` (`ID_USUARIO`) ON DELETE CASCADE
) ENGINE=InnoDB 
  DEFAULT CHARSET=utf8mb4 
  COLLATE=utf8mb4_unicode_ci;



DROP TABLE IF EXISTS `TAGS`;

CREATE TABLE `TAGS` (
  `ID_TAG` int NOT NULL AUTO_INCREMENT,
  `NOME_TAG` varchar(40) NOT NULL,
  PRIMARY KEY (`ID_TAG`)
) ENGINE=InnoDB 
  AUTO_INCREMENT=84 
  DEFAULT CHARSET=utf8;




DROP TABLE IF EXISTS `TAGS_PORTFOLIOS`;

CREATE TABLE `TAGS_PORTFOLIOS` (
  `ID_TAG` int NOT NULL,
  `ID_PORTFOLIO` int NOT NULL,
  KEY `idx_tag_portfolio` (`ID_TAG`,`ID_PORTFOLIO`),
  KEY `FK_TAGS_PORTFOLIOS_PORTFOLIO` (`ID_PORTFOLIO`),
  CONSTRAINT `FK_TAGS_PORTFOLIOS_PORTFOLIO` FOREIGN KEY (`ID_PORTFOLIO`) REFERENCES `PORTFOLIOS` (`ID_PORTFOLIO`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_TAGS_PORTFOLIOS_TAG` FOREIGN KEY (`ID_TAG`) REFERENCES `TAGS` (`ID_TAG`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB 
  DEFAULT CHARSET=utf8mb4 
  COLLATE=utf8mb4_unicode_ci;




DROP TABLE IF EXISTS `TAGS_PUBLICACOES`;

CREATE TABLE `TAGS_PUBLICACOES` (
  `ID_TAG` int NOT NULL,
  `ID_PUBLICACAO` int NOT NULL,
  KEY `ID_TAG` (`ID_TAG`),
  KEY `ID_PUBLICACAO` (`ID_PUBLICACAO`),
  CONSTRAINT `TAGS_PUBLICACOES_ibfk_1` FOREIGN KEY (`ID_TAG`) REFERENCES `TAGS` (`ID_TAG`) ON DELETE CASCADE,
  CONSTRAINT `TAGS_PUBLICACOES_ibfk_2` FOREIGN KEY (`ID_PUBLICACAO`) REFERENCES `PUBLICACOES_PROFISSIONAL` (`ID_PUBLICACAO`) ON DELETE CASCADE
) ENGINE=InnoDB 
  DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `TIPOS_PENALIDADES`;

CREATE TABLE `TIPOS_PENALIDADES` (
  `ID_PENALIDADE` int NOT NULL AUTO_INCREMENT,
  `NOME_PENALIDADE` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`ID_PENALIDADE`),
  UNIQUE KEY `NOME_PENALIDADE` (`NOME_PENALIDADE`)
) ENGINE=InnoDB 
  DEFAULT CHARSET=utf8mb4 
  COLLATE=utf8mb4_unicode_ci;



DROP TABLE IF EXISTS `USUARIO_PROFISSIONAL`;

CREATE TABLE `USUARIO_PROFISSIONAL` (
  `ID_USUARIO` int NOT NULL,
  `DIPLOMA_DESIGNER` longblob,
  `ESPECIALIZACAO_DESIGNER` varchar(70) DEFAULT NULL,
  `MEDIA_AVALIACOES_PROFISSIONAL` decimal(3,2) DEFAULT NULL,
  PRIMARY KEY (`ID_USUARIO`),
  CONSTRAINT `USUARIO_PROFISSIONAL_ibfk_1` FOREIGN KEY (`ID_USUARIO`) REFERENCES `USUARIOS` (`ID_USUARIO`) ON DELETE CASCADE
) ENGINE=InnoDB 
  DEFAULT CHARSET=utf8;








DROP TABLE IF EXISTS `USUARIOS`;

CREATE TABLE `USUARIOS` (
  `ID_USUARIO` int NOT NULL AUTO_INCREMENT,
  `NOME_USUARIO` varchar(70) NOT NULL,
  `EMAIL_USUARIO` varchar(100) NOT NULL,
  `CELULAR_USUARIO` char(11) NOT NULL,
  `SENHA_USUARIO` varchar(255) NOT NULL,
  `CPF_USUARIO` char(11) NOT NULL,
  `DATA_NASC_USUARIO` date NOT NULL,
  `GENERO_USUARIO` enum('feminino','masculino','prefiro não dizer','outro') DEFAULT NULL,
  `FOTO_PERFIL_BANCO_USUARIO` longblob,
  `IMG_BANNER_PASTA_USUARIO` varchar(80) DEFAULT NULL,
  `TIPO_USUARIO` enum('comum','profissional','administrador') NOT NULL,
  `STATUS_USUARIO` enum('ativo','inativo','suspenso','pendente') NOT NULL DEFAULT 'pendente',
  `USER_USUARIO` varchar(30) NOT NULL,
  `FOTO_PERFIL_PASTA_USUARIO` varchar(80) DEFAULT NULL,
  `IMG_BANNER_BANCO_USUARIO` longblob,
  `DESCRICAO_PERFIL_USUARIO` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `LINKEDIN_USUARIO` varchar(200) DEFAULT NULL,
  `PINTEREST_USUARIO` varchar(200) DEFAULT NULL,
  `INSTAGRAM_USUARIO` varchar(200) DEFAULT NULL,
  `WHATSAPP_USUARIO` varchar(200) DEFAULT NULL,
  DATA_CADASTRO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID_USUARIO`),
  UNIQUE KEY `EMAIL_USUARIO` (`EMAIL_USUARIO`),
  UNIQUE KEY `CELULAR_USUARIO` (`CELULAR_USUARIO`),
  UNIQUE KEY `CPF_USUARIO` (`CPF_USUARIO`)
) ENGINE=InnoDB 
  AUTO_INCREMENT=17 
  DEFAULT CHARSET=utf8;






DROP TABLE IF EXISTS `VISUALIZACOES_PUBLICACAO`;

CREATE TABLE `VISUALIZACOES_PUBLICACAO` (
  `ID_VISUALIZACAO` int NOT NULL AUTO_INCREMENT,
  `ID_PUBLICACAO` int NOT NULL,
  `ID_USUARIO` int DEFAULT NULL,
  `TOKEN_SESSAO` varchar(100) DEFAULT NULL,
  `DATA_VISUALIZACAO` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID_VISUALIZACAO`),
  KEY `fk_publi_visu` (`ID_PUBLICACAO`),
  KEY `fk_user_visu` (`ID_USUARIO`),
  CONSTRAINT `fk_publi_visu` FOREIGN KEY (`ID_PUBLICACAO`) REFERENCES `PUBLICACOES_PROFISSIONAL` (`ID_PUBLICACAO`) ON DELETE CASCADE,
  CONSTRAINT `fk_user_visu` FOREIGN KEY (`ID_USUARIO`) REFERENCES `USUARIOS` (`ID_USUARIO`) ON DELETE SET NULL
) ENGINE=InnoDB 
  AUTO_INCREMENT=4 
  DEFAULT CHARSET=utf8;







CREATE TABLE AVALIACOES_PROFISSIONAL (
    ID_AVALIACAO INT AUTO_INCREMENT PRIMARY KEY,
    ID_PROFISSIONAL INT NOT NULL,
    ID_AVALIADOR INT NOT NULL,
    COMENTARIO TEXT,
    NOTA TINYINT NOT NULL CHECK (NOTA >= 1 AND NOTA <= 5),
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT fk_profissional
        FOREIGN KEY (ID_PROFISSIONAL) REFERENCES USUARIOS(ID_USUARIO)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
        
    CONSTRAINT fk_avaliador
        FOREIGN KEY (ID_AVALIADOR) REFERENCES USUARIOS(ID_USUARIO)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);



CREATE TABLE MENSAGENS_QUEM_SOMOS (
    ID_MSG_QUEM_SOMOS INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME_PESSOA VARCHAR(150) NOT NULL,
    EMAIL_PESSOA VARCHAR(150) NOT NULL,
    CELULAR_PESSOA VARCHAR(50) DEFAULT NULL,
    MENSAGEM TEXT NOT NULL,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
