
CREATE TABLE `USUARIOS` (
  `ID_USUARIO` int NOT NULL AUTO_INCREMENT,
  `NOME_USUARIO` varchar(70) NOT NULL,
  `EMAIL_USUARIO` varchar(100) NOT NULL,
  `CELULAR_USUARIO` char(11) NOT NULL,
  `SENHA_USUARIO` varchar(255) NOT NULL,
  `CPF_USUARIO` char(11) NOT NULL,
  `DATA_NASC_USUARIO` date NOT NULL,
  `GENERO_USUARIO` enum('feminino','masculino','prefiro não dizer','outro') DEFAULT NULL,
  `FOTO_PERFIL_BANCO_USUARIO` longblob,
  `IMG_BANNER_PASTA_USUARIO` varchar(80) DEFAULT NULL,
  `TIPO_USUARIO` enum('comum','profissional','administrador') NOT NULL,
  `STATUS_USUARIO` enum('ativo','inativo','suspenso','pendente') NOT NULL DEFAULT 'pendente',
  `USER_USUARIO` varchar(30) NOT NULL,
  `FOTO_PERFIL_PASTA_USUARIO` varchar(80) DEFAULT NULL,
  `IMG_BANNER_BANCO_USUARIO` longblob,
  `DESCRICAO_PERFIL_USUARIO` varchar(1000) DEFAULT NULL,
  `LINKEDIN_USUARIO` varchar(200) DEFAULT NULL,
  `PINTEREST_USUARIO` varchar(200) DEFAULT NULL,
  `INSTAGRAM_USUARIO` varchar(200) DEFAULT NULL,
  `WHATSAPP_USUARIO` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`ID_USUARIO`),
  UNIQUE KEY `EMAIL_USUARIO` (`EMAIL_USUARIO`),
  UNIQUE KEY `CELULAR_USUARIO` (`CELULAR_USUARIO`),
  UNIQUE KEY `CPF_USUARIO` (`CPF_USUARIO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;




CREATE TABLE `USUARIO_PROFISSIONAL` (
  `ID_USUARIO` int NOT NULL,
  `DIPLOMA_DESIGNER` longblob,
  `ESPECIALIZACAO_DESIGNER` varchar(70) DEFAULT NULL,
  PRIMARY KEY (`ID_USUARIO`),
  CONSTRAINT `USUARIO_PROFISSIONAL_ibfk_1` 
    FOREIGN KEY (`ID_USUARIO`) 
    REFERENCES `USUARIOS` (`ID_USUARIO`) 
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `PUBLICACOES_PROFISSIONAL`;

CREATE TABLE `PUBLICACOES_PROFISSIONAL` (
  `ID_PUBLICACAO` int NOT NULL AUTO_INCREMENT,
  `ID_USUARIO` int NOT NULL,
  `NOME_PUBLICACAO` varchar(70) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `DESCRICAO_PUBLICACAO` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `CATEGORIA` varchar(50) NOT NULL,
  PRIMARY KEY (`ID_PUBLICACAO`),
  KEY `ID_USUARIO` (`ID_USUARIO`),
  CONSTRAINT `PUBLICACOES_PROFISSIONAL_ibfk_1` 
    FOREIGN KEY (`ID_USUARIO`) 
    REFERENCES `USUARIOS` (`ID_USUARIO`) 
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;





DROP TABLE IF EXISTS `CONTEUDOS_PUBLICACAO_PROFISSIONAL`;

CREATE TABLE `CONTEUDOS_PUBLICACAO_PROFISSIONAL` (
  `ID_PUBLICACAO` int NOT NULL,
  `IMG_PUBLICACAO` longblob,
  KEY `ID_PUBLICACAO` (`ID_PUBLICACAO`),
  CONSTRAINT `CONTEUDOS_PUBLICACAO_PROFISSIONAL_ibfk_1` 
    FOREIGN KEY (`ID_PUBLICACAO`) 
    REFERENCES `PUBLICACOES_PROFISSIONAL` (`ID_PUBLICACAO`) 
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



DROP TABLE IF EXISTS `TAGS`;

CREATE TABLE `TAGS` (
  `ID_TAG` int NOT NULL AUTO_INCREMENT,
  `NOME_TAG` varchar(40) NOT NULL,
  PRIMARY KEY (`ID_TAG`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;




DROP TABLE IF EXISTS `TAGS_PUBLICACOES`;

CREATE TABLE `TAGS_PUBLICACOES` (
  `ID_TAG` int NOT NULL,
  `ID_PUBLICACAO` int NOT NULL,
  KEY `ID_TAG` (`ID_TAG`),
  KEY `ID_PUBLICACAO` (`ID_PUBLICACAO`),
  CONSTRAINT `TAGS_PUBLICACOES_ibfk_1` 
    FOREIGN KEY (`ID_TAG`) 
    REFERENCES `TAGS` (`ID_TAG`) 
    ON DELETE CASCADE,
  CONSTRAINT `TAGS_PUBLICACOES_ibfk_2` 
    FOREIGN KEY (`ID_PUBLICACAO`) 
    REFERENCES `PUBLICACOES_PROFISSIONAL` (`ID_PUBLICACAO`) 
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



DROP TABLE IF EXISTS `FAVORITOS`;

CREATE TABLE `FAVORITOS` (
  `ID_PUBLICACAO` int NOT NULL,
  `ID_USUARIO` int NOT NULL,
  `DT_INCLUSAO_FAVORITO` date DEFAULT NULL,
  `STATUS_FAVORITO` int DEFAULT 1,
  PRIMARY KEY (`ID_PUBLICACAO`,`ID_USUARIO`),
  KEY `FK_FAVORITO_USUARIO` (`ID_USUARIO`),
  KEY `FK_FAVORITO_PUBLICACAO` (`ID_PUBLICACAO`),
  CONSTRAINT `FK_FAVORITO_PUBLICACAO` 
    FOREIGN KEY (`ID_PUBLICACAO`) 
    REFERENCES `PUBLICACOES_PROFISSIONAL` (`ID_PUBLICACAO`),
  CONSTRAINT `FK_FAVORITO_USUARIO` 
    FOREIGN KEY (`ID_USUARIO`) 
    REFERENCES `USUARIOS` (`ID_USUARIO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `PORTFOLIOS` (
  `ID_PORTFOLIO` int NOT NULL AUTO_INCREMENT,
  `NOME_PORTFOLIO` varchar(70) NOT NULL,
  `ID_USUARIO` int NOT NULL,
  `DESCRICAO_PORTFOLIO` text,
  PRIMARY KEY (`ID_PORTFOLIO`),
  KEY `ID_USUARIO` (`ID_USUARIO`),
  CONSTRAINT `PORTFOLIOS_ibfk_1` FOREIGN KEY (`ID_USUARIO`) REFERENCES `USUARIOS` (`ID_USUARIO`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



CREATE TABLE `PUBLICACAO_PORTFOLIO` (
  `ID_PUBLICACAO` int NOT NULL,
  `ID_PORTFOLIO` int NOT NULL,
  PRIMARY KEY (`ID_PUBLICACAO`,`ID_PORTFOLIO`),
  KEY `ID_PORTFOLIO` (`ID_PORTFOLIO`),
  CONSTRAINT `PUBLICACAO_PORTFOLIO_ibfk_1` FOREIGN KEY (`ID_PUBLICACAO`) REFERENCES `PUBLICACOES_PROFISSIONAL` (`ID_PUBLICACAO`) ON DELETE CASCADE,
  CONSTRAINT `PUBLICACAO_PORTFOLIO_ibfk_2` FOREIGN KEY (`ID_PORTFOLIO`) REFERENCES `PORTFOLIOS` (`ID_PORTFOLIO`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;




CREATE TABLE `TAGS_PORTFOLIOS` (
  `ID_TAG` int NOT NULL,
  `ID_PORTFOLIO` int NOT NULL,
  KEY `idx_tag_portfolio` (`ID_TAG`,`ID_PORTFOLIO`),
  KEY `FK_TAGS_PORTFOLIOS_PORTFOLIO` (`ID_PORTFOLIO`),
  CONSTRAINT `FK_TAGS_PORTFOLIOS_PORTFOLIO` FOREIGN KEY (`ID_PORTFOLIO`) REFERENCES `PORTFOLIOS` (`ID_PORTFOLIO`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_TAGS_PORTFOLIOS_TAG` FOREIGN KEY (`ID_TAG`) REFERENCES `TAGS` (`ID_TAG`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;




DROP TABLE IF EXISTS `PROPOSTA_PROJETO`;

CREATE TABLE `PROPOSTA_PROJETO` (
  `ID_PROPOSTA` int NOT NULL AUTO_INCREMENT,
  `ID_USUARIO` int NOT NULL,
  `DATA_PROPOSTA` date NOT NULL,
  `TITULO_PROPOSTA` varchar(70) NOT NULL,
  `DESCRICAO_PROPOSTA` text NOT NULL,
  `CATEGORIA_PROPOSTA` varchar(50) NOT NULL,
  `PREFERENCIA_PROPOSTA` varchar(50) DEFAULT NULL,
  `PRAZO_ENTREGA` date DEFAULT NULL,
  `ORCAMENTO` decimal(10,2) DEFAULT NULL,
  `STATUS_PROPOSTA` enum('Aberta','Fechada','Expirada') NOT NULL,
  PRIMARY KEY (`ID_PROPOSTA`),
  KEY `ID_USUARIO` (`ID_USUARIO`),
  CONSTRAINT `PROPOSTA_PROJETO_ibfk_1` 
    FOREIGN KEY (`ID_USUARIO`) 
    REFERENCES `USUARIOS` (`ID_USUARIO`) 
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



DROP TABLE IF EXISTS `CHATS`;

CREATE TABLE `CHATS` (
  `ID_CHAT` int NOT NULL AUTO_INCREMENT,
  `ID_USUARIO_1` int NOT NULL,
  `ID_USUARIO_2` int NOT NULL,
  PRIMARY KEY (`ID_CHAT`),
  KEY `ID_USUARIO_1` (`ID_USUARIO_1`),
  KEY `ID_USUARIO_2` (`ID_USUARIO_2`),
  CONSTRAINT `CHATS_ibfk_1` 
    FOREIGN KEY (`ID_USUARIO_1`) 
    REFERENCES `USUARIOS` (`ID_USUARIO`) 
    ON DELETE CASCADE,
  CONSTRAINT `CHATS_ibfk_2` 
    FOREIGN KEY (`ID_USUARIO_2`) 
    REFERENCES `USUARIOS` (`ID_USUARIO`) 
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



DROP TABLE IF EXISTS `COMENTARIOS`;

CREATE TABLE `COMENTARIOS` (
  `ID_COMENTARIO` int NOT NULL AUTO_INCREMENT,
  `ID_USUARIO` int NOT NULL,
  `ID_PUBLICACAO` int NOT NULL,
  `CONTEUDO_COMENTARIO` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `DATA_COMENTARIO` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID_COMENTARIO`),
  KEY `ID_USUARIO` (`ID_USUARIO`),
  KEY `ID_PUBLICACAO` (`ID_PUBLICACAO`),
  CONSTRAINT `COMENTARIOS_ibfk_1` 
    FOREIGN KEY (`ID_USUARIO`) 
    REFERENCES `USUARIOS` (`ID_USUARIO`) 
    ON DELETE CASCADE,
  CONSTRAINT `COMENTARIOS_ibfk_2` 
    FOREIGN KEY (`ID_PUBLICACAO`) 
    REFERENCES `PUBLICACOES_PROFISSIONAL` (`ID_PUBLICACAO`) 
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;








DROP TABLE IF EXISTS `DENUNCIAS_COMENTARIOS`;

CREATE TABLE `DENUNCIAS_COMENTARIOS` (
  `ID_DENUNCIA` int NOT NULL AUTO_INCREMENT,
  `ID_USUARIO_DENUNCIANTE` int NOT NULL,
  `ID_COMENTARIO` int NOT NULL,
  `MOTIVO` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `STATUS` enum('pendente','analisando','resolvido') COLLATE utf8mb4_unicode_ci DEFAULT 'pendente',
  `DATA_DENUNCIA` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID_DENUNCIA`),
  KEY `ID_USUARIO_DENUNCIANTE` (`ID_USUARIO_DENUNCIANTE`),
  KEY `ID_COMENTARIO` (`ID_COMENTARIO`),
  CONSTRAINT `DENUNCIAS_COMENTARIOS_ibfk_1` 
    FOREIGN KEY (`ID_USUARIO_DENUNCIANTE`) 
    REFERENCES `USUARIOS` (`ID_USUARIO`),
  CONSTRAINT `DENUNCIAS_COMENTARIOS_ibfk_2` 
    FOREIGN KEY (`ID_COMENTARIO`) 
    REFERENCES `COMENTARIOS` (`ID_COMENTARIO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;



DROP TABLE IF EXISTS `DENUNCIAS_USUARIOS`;

CREATE TABLE `DENUNCIAS_USUARIOS` (
  `ID_DENUNCIA` int NOT NULL AUTO_INCREMENT,
  `ID_USUARIO_DENUNCIANTE` int NOT NULL,
  `ID_USUARIO_DENUNCIADO` int NOT NULL,
  `MOTIVO` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `STATUS` enum('pendente','analisando','resolvido') COLLATE utf8mb4_unicode_ci DEFAULT 'pendente',
  `DATA_DENUNCIA` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID_DENUNCIA`),
  KEY `ID_USUARIO_DENUNCIANTE` (`ID_USUARIO_DENUNCIANTE`),
  KEY `ID_USUARIO_DENUNCIADO` (`ID_USUARIO_DENUNCIADO`),
  CONSTRAINT `DENUNCIAS_USUARIOS_ibfk_1` 
    FOREIGN KEY (`ID_USUARIO_DENUNCIANTE`) 
    REFERENCES `USUARIOS` (`ID_USUARIO`),
  CONSTRAINT `DENUNCIAS_USUARIOS_ibfk_2` 
    FOREIGN KEY (`ID_USUARIO_DENUNCIADO`) 
    REFERENCES `USUARIOS` (`ID_USUARIO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;



SHOW CREATE TABLE DENUNCIAS_COMENTARIOS;

ALTER TABLE DENUNCIAS_COMENTARIOS 
DROP FOREIGN KEY DENUNCIAS_COMENTARIOS_ibfk_2;

ALTER TABLE DENUNCIAS_COMENTARIOS
ADD CONSTRAINT DENUNCIAS_COMENTARIOS_ibfk_2
FOREIGN KEY (ID_COMENTARIO) REFERENCES COMENTARIOS(ID_COMENTARIO)
ON DELETE CASCADE;

DROP TABLE IF EXISTS `MENSAGENS`;

CREATE TABLE `MENSAGENS` (
  `ID_MSG` int NOT NULL AUTO_INCREMENT,
  `ID_CHAT` int NOT NULL,
  `REMETENTE_MSG` int NOT NULL,
  `DESTINATARIO_MSG` int NOT NULL,
  `CONTEUDO_MSG` text NOT NULL,
  `DATA_MSG` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID_MSG`),
  KEY `ID_CHAT` (`ID_CHAT`),
  KEY `REMETENTE_MSG` (`REMETENTE_MSG`),
  KEY `DESTINATARIO_MSG` (`DESTINATARIO_MSG`),
  CONSTRAINT `MENSAGENS_ibfk_1` 
    FOREIGN KEY (`ID_CHAT`) 
    REFERENCES `CHATS` (`ID_CHAT`) 
    ON DELETE CASCADE,
  CONSTRAINT `MENSAGENS_ibfk_2` 
    FOREIGN KEY (`REMETENTE_MSG`) 
    REFERENCES `USUARIOS` (`ID_USUARIO`) 
    ON DELETE CASCADE,
  CONSTRAINT `MENSAGENS_ibfk_3` 
    FOREIGN KEY (`DESTINATARIO_MSG`) 
    REFERENCES `USUARIOS` (`ID_USUARIO`) 
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



DROP TABLE IF EXISTS `PENALIDADES`;

CREATE TABLE `PENALIDADES` (
  `ID_PENALIDADE` int NOT NULL AUTO_INCREMENT,
  `TIPO_ID` int NOT NULL,
  `PERIODO_PENALIDADE` int DEFAULT NULL,
  `MOTIVO_PENALIDADE` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `DATA_APLICACAO` date NOT NULL,
  PRIMARY KEY (`ID_PENALIDADE`),
  KEY `TIPO_ID` (`TIPO_ID`),
  CONSTRAINT `PENALIDADES_ibfk_1` 
    FOREIGN KEY (`TIPO_ID`) 
    REFERENCES `TIPOS_PENALIDADES` (`ID_PENALIDADE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;




DROP TABLE IF EXISTS `TIPOS_PENALIDADES`;

CREATE TABLE `TIPOS_PENALIDADES` (
  `ID_PENALIDADE` int NOT NULL AUTO_INCREMENT,
  `NOME_PENALIDADE` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`ID_PENALIDADE`),
  UNIQUE KEY `NOME_PENALIDADE` (`NOME_PENALIDADE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

